replicaCount: 1

image:
  repository: ghcr.io/fin-lending/loan-service-ui
  tag: "latest"
  pullPolicy: Always

imagePullSecrets:
  - name: ghcr-pull-secret

ingress:
  enabled: true
  className: "lending-private"
  hosts:
    - host: loan-service-ui.demo.local
      paths:
        - path: /
          pathType: Prefix

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi
