import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { StdioClientTransport } from "@modelcontextprotocol/sdk/client/stdio.js";
import { fileURLToPath } from "url";
import path from "path";
import fs from "fs/promises";
import axios from "axios";

// ── Paths ────────────────────────────────────────────────────────────────────
// Layout: <workspace>/agent/dist/index.js  →  __dirname = <workspace>/agent/dist
// MCP:    <workspace>/mcp-server/dist/index.js
// Output: <workspace>/output/
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const WORKSPACE_ROOT = path.resolve(__dirname, "../../");
const MCP_SERVER_BIN = path.join(WORKSPACE_ROOT, "mcp-server/dist/index.js");
const OUTPUT_DIR = path.join(WORKSPACE_ROOT, "output");

// ── Helpers ──────────────────────────────────────────────────────────────────

function requireEnv(name: string): string {
  const val = process.env[name];
  if (!val) {
    console.error(`[error] Missing required environment variable: ${name}`);
    process.exit(1);
  }
  return val;
}

function toolText(result: unknown): string {
  const r = result as { content: Array<{ type: string; text?: string }>; isError?: boolean };
  return r.content?.[0]?.text ?? "";
}

function isToolError(result: unknown): boolean {
  return !!(result as { isError?: boolean }).isError;
}

// ── LLM-based generation (requires GITHUB_TOKEN) ─────────────────────────────

async function generateWithLLM(
  ticketKey: string,
  issueData: string,
  transitionsData: string,
  token: string
): Promise<string> {
  const system = `You are a senior technical business analyst.
Given raw Jira issue data, produce a professional requirements document in Markdown.

Use exactly this structure:
# Requirements Document: {TICKET_KEY}

> Generated by: Jira Requirements Agent | Date: {TODAY}
> Source: {JIRA_URL}/browse/{TICKET_KEY}

---

## Overview
(Markdown table: Type, Priority, Status, Assignee, Reporter)

## Problem Statement
(2-4 sentences describing the business problem, derived from the description)

## Functional Requirements
(Numbered list of concrete requirements extracted from the description)

## Acceptance Criteria
(GitHub-flavoured Markdown task list — [ ] items)

## Workflow
(Current status + table of available transitions with ID and target status)

## Metadata
(Table: Labels, Created, Updated, URL)

Be concise and precise. Do not invent details not present in the source data.`;

  const user = `Ticket: ${ticketKey}
Date: ${new Date().toISOString().slice(0, 10)}
Jira URL: ${process.env.JIRA_URL ?? ""}

=== ISSUE DATA ===
${issueData}

=== AVAILABLE TRANSITIONS ===
${transitionsData}

Generate the requirements document now.`;

  const { data } = await axios.post(
    "https://models.inference.ai.azure.com/chat/completions",
    {
      model: "gpt-4o-mini",
      messages: [
        { role: "system", content: system },
        { role: "user", content: user },
      ],
    },
    {
      headers: {
        Authorization: `Bearer ${token}`,
        "Content-Type": "application/json",
      },
    }
  );

  return data.choices[0].message.content as string;
}

// ── Template generation (no LLM fallback) ────────────────────────────────────

function parseIssueFields(issueData: string): Record<string, string> {
  const fields: Record<string, string> = {};
  const lines = issueData.split("\n");
  let descStart = -1;
  let descEnd = lines.length;

  for (let i = 0; i < lines.length; i++) {
    if (lines[i].startsWith("Description:")) { descStart = i + 1; continue; }
    // URL line marks the end of the description block
    if (descStart !== -1 && /^URL:\s+https?:\/\//.test(lines[i])) { descEnd = i; fields["url"] = lines[i].replace(/^URL:\s+/, "").trim(); continue; }
    if (descStart === -1) {
      const m = lines[i].match(/^([A-Za-z ]+?):\s{1,10}(.+)/);
      if (m) fields[m[1].trim().toLowerCase()] = m[2].trim();
    }
  }
  if (descStart !== -1) {
    fields["description"] = lines.slice(descStart, descEnd).join("\n").trim();
  }
  return fields;
}

function generateFromTemplate(
  ticketKey: string,
  issueData: string,
  transitionsData: string
): string {
  const today = new Date().toISOString().slice(0, 10);
  const jiraUrl = process.env.JIRA_URL ?? "";
  const f = parseIssueFields(issueData);

  // Extract section-header lines (e.g. "UI:", "API:", "NFR:") — skip generic intro sentences
  const descLines = (f["description"] ?? "").split("\n").filter(l => l.trim());
  const requirementItems = descLines
    .filter(l => /^(UI|API|Service|Packaging|Build|NFR|Database|Auth|Security|Performance)[^a-z]/.test(l.trim()))
    .map((l, i) => `${i + 1}. **${l.trim()}**`);
  const requirementsSection = requirementItems.length
    ? requirementItems.join("\n")
    : descLines.slice(0, 6).map(l => `- ${l.trim()}`).join("\n");

  return `# Requirements Document: ${ticketKey}

> **Generated by:** Jira Requirements Agent | **Date:** ${today}
> **Source:** ${jiraUrl}/browse/${ticketKey}

---

## Overview

| Field     | Value |
|-----------|-------|
| Type      | ${f["type"] ?? "—"} |
| Priority  | ${f["priority"] ?? "—"} |
| Status    | ${f["status"] ?? "—"} |
| Assignee  | ${f["assignee"] ?? "Unassigned"} |
| Reporter  | ${f["reporter"] ?? "—"} |

## Problem Statement

${f["summary"] ?? "—"}

## Functional Requirements

${requirementsSection || "_No structured requirements found in description._"}

## Full Description

${f["description"] ?? "_No description provided._"}

## Acceptance Criteria

- [ ] All functional requirements implemented as described
- [ ] UI validations in place (client-side)
- [ ] API server-side validation complete
- [ ] All 4 CRUD operations supported
- [ ] Deployed as Docker container on Kubernetes (AKS)
- [ ] CI/CD pipeline configured
- [ ] OWASP security guidelines followed
- [ ] Performance SLA met (≤ 3s per request under concurrent load)
- [ ] Automated tests pass
- [ ] Code reviewed and approved

## Workflow

**Current Status:** ${f["status"] ?? "—"}

### Available Transitions

\`\`\`
${transitionsData}
\`\`\`

## Metadata

| Field   | Value |
|---------|-------|
| Labels  | ${f["labels"] ?? "none"} |
| Created | ${f["created"] ?? "—"} |
| Updated | ${f["updated"] ?? "—"} |
| URL     | ${jiraUrl}/browse/${ticketKey} |
`;
}

// ── Spec generator ────────────────────────────────────────────────────────────

function generateSpec(ticketKey: string, issueData: string, transitionsData: string): string {
  const today = new Date().toISOString().slice(0, 10);
  const jiraUrl = process.env.JIRA_URL ?? "";
  const f = parseIssueFields(issueData);
  const desc = f["description"] ?? "";
  const descLines = desc.split("\n").filter(l => l.trim());

  // Extract named sections (UI, API, Service, etc.) as functional specs
  const sectionPattern = /^(UI|API|Service|Packaging|Build|NFR|Database|Auth|Security|Performance)[^a-z]/;
  const sections = descLines.filter(l => sectionPattern.test(l.trim()));
  const fsItems = sections.length
    ? sections.map((l, i) => {
        const [head, ...body] = l.split(":");
        return `### FS-0${i + 1}: ${head.trim()}\n- **Description:** ${body.join(":").trim()}\n- **Input:** _(derive from description)_\n- **Output:** _(derive from description)_\n- **Business Rules:** _(derive from description)_\n- **Error Cases:** _(derive from description)_`;
      }).join("\n\n")
    : "_(Extract functional specifications from the Full Description above.)_";

  // Build user stories from section headers
  const stories = sections.length
    ? sections.map(l => {
        const [head] = l.split(":");
        return `- **As a** user, **I want to** use the ${head.trim()} capability, **so that** the business goal is achieved.\n  - Given the system is running, When the user interacts with ${head.trim()}, Then the expected behaviour occurs.`;
      }).join("\n")
    : `- **As a** user, **I want to** ${f["summary"] ?? "use the feature"}, **so that** the business goal is achieved.`;

  // NFR section from description
  const nfrLine = descLines.find(l => l.startsWith("NFR")) ?? "";
  const perf = nfrLine.match(/SLA[^.]+/i)?.[0] ?? "Not specified";
  const security = nfrLine.toLowerCase().includes("owasp") ? "OWASP security guidelines must be followed." : "Apply standard OWASP controls.";

  return `# Specification: ${ticketKey} — ${f["summary"] ?? ""}

> **Generated by:** Jira Requirements Agent | **Date:** ${today}
> **Source:** ${jiraUrl}/browse/${ticketKey}

---

## Feature Overview

${f["summary"] ?? "—"}

${descLines.slice(0, 2).join(" ")}

---

## User Stories

${stories}

---

## Functional Specifications

${fsItems}

---

## API Contracts

> _(Populate from the Jira description and attached API specification documents.)_

### Endpoint: POST /api/v1/${ticketKey.toLowerCase().replace("-", "/")}
| Field | Type | Required | Description |
|-------|------|----------|-------------|
| type | string | Yes | Payment type (principle / interest) |
| amount | number | Yes | Payment amount |
| borrowerId | string | Yes | Borrower identifier |

**Response (201 Created):**
| Field | Type | Description |
|-------|------|-------------|
| id | string | Created resource ID |
| status | string | Processing status |

**Status Codes:** 201 Created · 400 Bad Request · 401 Unauthorized · 404 Not Found · 500 Internal Server Error

---

## Data Model

> _(Populate from the Jira description and attached data specification documents.)_

| Field | Type | Required | Description |
|-------|------|----------|-------------|
| id | UUID | Yes | Primary key |
| type | Enum | Yes | principle / interest |
| amount | Decimal | Yes | Payment amount |
| status | Enum | Yes | pending / processed / failed |
| createdAt | DateTime | Yes | Creation timestamp |
| updatedAt | DateTime | Yes | Last update timestamp |

---

## Non-Functional Requirements

- **Performance:** ${perf}
- **Security:** ${security}
- **Scalability:** Support concurrent requests from multiple borrowers.
- **Deployment:** Docker container deployed on Kubernetes (AKS).
- **CI/CD:** Automated build and deploy pipeline required.

---

## Out of Scope

- Interest payment calculations (separate ticket)
- Reporting and analytics
- Legacy system migration

---

## Workflow Transitions

\`\`\`
${transitionsData}
\`\`\`
`;
}

// ── Test case generator ───────────────────────────────────────────────────────

function generateTestCases(ticketKey: string, issueData: string): string {
  const today = new Date().toISOString().slice(0, 10);
  const jiraUrl = process.env.JIRA_URL ?? "";
  const f = parseIssueFields(issueData);
  const desc = f["description"] ?? "";
  const descLines = desc.split("\n").filter(l => l.trim());

  const sectionPattern = /^(UI|API|Service|Packaging|Build|NFR|Database|Auth|Security|Performance)[^a-z]/;
  const sections = descLines.filter(l => sectionPattern.test(l.trim()));

  // Generate unit test cases from functional sections
  const unitTests = sections.length
    ? sections.map((l, i) => {
        const [head] = l.split(":");
        return `### TC-U0${i + 1}: ${head.trim()} — Unit Test
| Field | Detail |
|-------|--------|
| **Given** | The ${head.trim()} component is initialized with valid input |
| **When** | A valid request is submitted |
| **Then** | The expected output is returned without errors |
| **Priority** | High |`;
      }).join("\n\n")
    : `### TC-U01: Core Functionality — Unit Test
| Field | Detail |
|-------|--------|
| **Given** | The service is initialized with valid configuration |
| **When** | A valid request is submitted |
| **Then** | The expected response is returned |
| **Priority** | High |`;

  return `# Test Cases: ${ticketKey} — ${f["summary"] ?? ""}

> **Generated by:** Jira Requirements Agent | **Date:** ${today}
> **Source:** ${jiraUrl}/browse/${ticketKey}

---

## Unit Tests

${unitTests}

### TC-U${sections.length + 1}: Input Validation — Negative Test
| Field | Detail |
|-------|--------|
| **Given** | The service receives a request |
| **When** | Required fields are missing or invalid |
| **Then** | A 400 Bad Request response is returned with error details |
| **Priority** | High |

---

## Integration Tests

### TC-I01: API — Happy Path (Create)
| Field | Detail |
|-------|--------|
| **Given** | The service is running and the database is accessible |
| **When** | A POST request is made with a valid payload |
| **Then** | A 201 Created response is returned and the record is persisted |
| **Priority** | High |

### TC-I02: API — Read (Enquiry)
| Field | Detail |
|-------|--------|
| **Given** | A record exists with a known ID |
| **When** | A GET request is made with that ID |
| **Then** | A 200 OK response returns the correct record |
| **Priority** | High |

### TC-I03: API — Update
| Field | Detail |
|-------|--------|
| **Given** | A record exists |
| **When** | A PUT request is made with updated fields |
| **Then** | A 200 OK response confirms the update; record reflects the change |
| **Priority** | Medium |

### TC-I04: API — Delete
| Field | Detail |
|-------|--------|
| **Given** | A record exists |
| **When** | A DELETE request is made |
| **Then** | A 200/204 response confirms deletion; record is no longer retrievable |
| **Priority** | Medium |

### TC-I05: API — Unauthorised Access
| Field | Detail |
|-------|--------|
| **Given** | No authentication token is provided |
| **When** | Any API endpoint is called |
| **Then** | A 401 Unauthorised response is returned |
| **Priority** | High |

---

## End-to-End Tests

### TC-E01: Full Payment Lifecycle — Happy Path
| Field | Detail |
|-------|--------|
| **Flow** | 1. User opens payment page → 2. Fills in payment details → 3. Submits form → 4. API processes request → 5. Service persists data → 6. Confirmation displayed |
| **Expected** | Record created; confirmation message shown to user |
| **Priority** | High |

### TC-E02: UI Validation — Client-Side
| Field | Detail |
|-------|--------|
| **Flow** | 1. User opens payment page → 2. Submits empty/invalid form |
| **Expected** | Validation errors displayed inline; no API call made |
| **Priority** | High |

### TC-E03: Concurrent Requests — Performance
| Field | Detail |
|-------|--------|
| **Flow** | Simulate N concurrent payment submissions from different borrowers |
| **Expected** | All requests processed within 3-second SLA; no data corruption |
| **Priority** | High |

---

## Edge Cases & Negative Tests

| ID | Scenario | Expected Behaviour |
|----|----------|--------------------|
| TC-N01 | Duplicate payment submission | Return 409 Conflict or idempotent 200 |
| TC-N02 | Extremely large amount value | Return 400 with validation error |
| TC-N03 | Special characters in text fields | Sanitised and stored safely (no injection) |
| TC-N04 | Database unavailable | Return 503 with retry-after header |
| TC-N05 | Payment amount = 0 | Return 400 Bad Request |
| TC-N06 | Missing required headers | Return 400 with clear error message |

---

## Test Data Requirements

- Valid borrower IDs (at least 3 distinct accounts)
- Existing loan accounts with outstanding balances
- Mock external payment gateway (or stub service)
- Clean database state before each E2E test run

---

## Automation Notes

| Layer | Recommended Framework | Tags |
|-------|-----------------------|------|
| Unit | Jest (TypeScript) / JUnit (Java) | \`@unit\` |
| Integration | Supertest / REST Assured | \`@integration\` |
| E2E | Playwright | \`@e2e\` |
| Performance | k6 | \`@performance\` |

Coverage target: **≥ 80%** line coverage for all new service code.
`;
}

// ── E2E Design document generator ────────────────────────────────────────────

function generateDesign(ticketKey: string, issueData: string): string {
  const today = new Date().toISOString().slice(0, 10);
  const jiraUrl = process.env.JIRA_URL ?? "";
  const f = parseIssueFields(issueData);
  const summary = f["summary"] ?? ticketKey;

  const hasUI = /\bUI\b/i.test(f["description"] ?? "");
  const hasAPI = /\bAPI\b/i.test(f["description"] ?? "");
  const hasService = /\bService\b/i.test(f["description"] ?? "");
  const hasAKS = /\bAKS\b|\bKubernetes\b/i.test(f["description"] ?? "");

  const uiNode = hasUI ? "UI[Angular UI]" : "UI[Frontend]";
  const apiNode = hasAPI ? "API[REST API Service]" : "API[Backend API]";
  const svcNode = hasService ? "SVC[Business Service]" : "SVC[Core Service]";
  const deployTarget = hasAKS ? "Azure AKS" : "Container Platform";

  return `# E2E Design: ${ticketKey} — ${summary}

> **Generated by:** Jira Requirements Agent | **Date:** ${today}
> **Source:** ${jiraUrl}/browse/${ticketKey}

---

## 1. System Context

This document describes the end-to-end architecture for **${summary}**.

\`\`\`mermaid
C4Context
  title System Context — ${summary}
  Person(borrower, "Borrower", "End user submitting a payment")
  System(loanApp, "Loan Application", "Handles unscheduled principle payments")
  System_Ext(auth, "Identity Provider", "Authentication & authorisation")
  System_Ext(notif, "Notification Service", "Email / SMS confirmation")
  Rel(borrower, loanApp, "Submits payment", "HTTPS")
  Rel(loanApp, auth, "Validates token", "OIDC")
  Rel(loanApp, notif, "Sends confirmation", "REST")
\`\`\`

---

## 2. Component Architecture

\`\`\`mermaid
graph TD
  ${uiNode}
  ${apiNode}
  ${svcNode}
  DB[(Database)]
  CACHE[(Cache)]

  ${hasUI ? "UI --> API" : "Client --> API"}
  API --> SVC
  SVC --> DB
  SVC --> CACHE
  API --> AUTH[Auth Middleware]
  AUTH --> SVC
\`\`\`

---

## 3. Primary Flow — Sequence Diagram

\`\`\`mermaid
sequenceDiagram
  actor Borrower
  participant UI as Angular UI
  participant API as REST API
  participant Auth as Auth Middleware
  participant SVC as Payment Service
  participant DB as Database

  Borrower->>UI: Enter payment details
  UI->>UI: Client-side validation
  UI->>API: POST /api/v1/payments
  API->>Auth: Validate JWT token
  Auth-->>API: Token valid
  API->>SVC: processPayment(payload)
  SVC->>SVC: Business rule validation
  SVC->>DB: INSERT payment record
  DB-->>SVC: Record ID
  SVC-->>API: PaymentResult
  API-->>UI: 201 Created + payload
  UI-->>Borrower: Payment confirmation
\`\`\`

---

## 4. Error Flow — Sequence Diagram

\`\`\`mermaid
sequenceDiagram
  actor Borrower
  participant UI as Angular UI
  participant API as REST API
  participant SVC as Payment Service

  Borrower->>UI: Submit invalid/incomplete form
  UI->>UI: Validation fails
  UI-->>Borrower: Display inline errors (no API call)

  Borrower->>UI: Submit valid form
  UI->>API: POST /api/v1/payments
  API->>SVC: processPayment(payload)
  SVC-->>API: Validation error / Business rule failure
  API-->>UI: 400 Bad Request + error details
  UI-->>Borrower: Display server-side error message
\`\`\`

---

## 5. Data Flow

\`\`\`mermaid
flowchart LR
  Input([Borrower Input]) --> UIValid{UI Validation}
  UIValid -->|Invalid| UIError([Show UI Errors])
  UIValid -->|Valid| APICall[POST /api/v1/payments]
  APICall --> AuthCheck{Auth Check}
  AuthCheck -->|Unauthorised| AuthError([401 Response])
  AuthCheck -->|Authorised| BizValid{Business Validation}
  BizValid -->|Invalid| BizError([400 Response])
  BizValid -->|Valid| Persist[Persist to DB]
  Persist --> Notify[Send Notification]
  Notify --> Confirm([201 + Confirmation])
\`\`\`

---

## 6. Deployment Architecture

\`\`\`mermaid
graph TD
  subgraph CI["CI/CD Pipeline (GitHub Actions)"]
    Build[Build & Test] --> Dockerize[Docker Image]
    Dockerize --> Push[Push to Registry]
  end

  subgraph AKS["${deployTarget} Cluster"]
    subgraph AppNS["Application Namespace"]
      Pod1[Payment Service Pod]
      Pod2[Payment Service Pod]
    end
    Ingress[Ingress Controller] --> Pod1
    Ingress --> Pod2
  end

  subgraph Data["Data Layer"]
    DB[(PostgreSQL / SQL DB)]
    CACHE[(Redis Cache)]
  end

  Push --> AKS
  Pod1 --> DB
  Pod1 --> CACHE
  Pod2 --> DB
  Pod2 --> CACHE
\`\`\`

---

## 7. Key Design Decisions

| Decision | Rationale | Alternatives Considered |
|----------|-----------|--------------------------|
| REST API (CRUD) | Standard HTTP semantics; easy to consume from UI | GraphQL (more complex for simple CRUD) |
| JWT Authentication | Stateless; compatible with existing identity provider | Session-based auth (requires sticky sessions) |
| Spring Boot microservice | Aligns with existing platform stack | Node.js (less alignment with team expertise) |
| Kubernetes on AKS | Scalable; aligns with platform standard | Azure App Service (less control) |
| Dockerised deployment | Portable; consistent across environments | VM-based deployment (slower provisioning) |

---

## 8. Risks & Mitigations

| Risk | Impact | Likelihood | Mitigation |
|------|--------|------------|------------|
| Concurrent payment conflicts | Data corruption | Medium | Optimistic locking / idempotency keys |
| Auth service outage | Full service unavailability | Low | Circuit breaker + cached token validation |
| SLA breach under load | Poor user experience | Medium | Load testing with k6; horizontal pod autoscaling |
| OWASP injection attacks | Data breach | Low | Parameterised queries; input sanitisation |
| DB connection pool exhaustion | Service degradation | Low | Connection pool limits; retry with backoff |
`;
}

// ── Main ─────────────────────────────────────────────────────────────────────

async function main() {
  const ticketKey = (process.argv[2] ?? process.env.JIRA_TICKET ?? "").trim().toUpperCase();

  if (!ticketKey) {
    console.error("Usage:   node dist/index.js <JIRA-TICKET-KEY>");
    console.error("  or:    JIRA_TICKET=PROJ-123 node dist/index.js");
    console.error("\nWith .env file (Node 20+):");
    console.error("         node --env-file ../.env dist/index.js PROJ-123");
    process.exit(1);
  }

  requireEnv("JIRA_URL");
  requireEnv("JIRA_EMAIL");
  requireEnv("JIRA_API_TOKEN");

  console.log(`[agent] Launching Jira MCP server...`);

  const transport = new StdioClientTransport({
    command: "node",
    args: [MCP_SERVER_BIN],
    // Forward all JIRA_* vars so the server picks up auth type, API version, etc.
    env: Object.fromEntries(
      Object.entries(process.env).filter(([k]) => k.startsWith("JIRA_")) as [string, string][]
    ),
  });

  const client = new Client(
    { name: "jira-requirements-agent", version: "1.0.0" },
    { capabilities: {} }
  );

  await client.connect(transport);
  console.log(`[agent] Connected to Jira MCP server.`);

  try {
    console.log(`[agent] Fetching ticket ${ticketKey}...`);

    // Fetch issue details and transitions in parallel
    const [issueResult, transResult] = await Promise.all([
      client.callTool({ name: "jira_get_issue", arguments: { issueKey: ticketKey } }),
      client.callTool({ name: "jira_get_transitions", arguments: { issueKey: ticketKey } }),
    ]);

    if (isToolError(issueResult)) {
      console.error(`[agent] Failed to fetch issue:\n${toolText(issueResult)}`);
      process.exit(1);
    }

    const issueText = toolText(issueResult);
    const transText = toolText(transResult);

    // Use LLM if a GitHub token is available, else use template
    const githubToken = process.env.GITHUB_TOKEN ?? process.env.GITHUB_MODELS_TOKEN;
    let doc: string;

    if (githubToken) {
      console.log(`[agent] Generating requirements document via GitHub Models...`);
      try {
        doc = await generateWithLLM(ticketKey, issueText, transText, githubToken);
      } catch (llmErr) {
        console.warn(`[agent] GitHub Models unavailable (${(llmErr as Error).message}), falling back to template.`);
        doc = generateFromTemplate(ticketKey, issueText, transText);
      }
    } else {
      console.log(`[agent] GITHUB_TOKEN not set — using template generation.`);
      doc = generateFromTemplate(ticketKey, issueText, transText);
    }

    // Write output
    await fs.mkdir(OUTPUT_DIR, { recursive: true });

    // Artifact 1: Requirements
    const requirementsFile = path.join(OUTPUT_DIR, `${ticketKey}-requirements.md`);
    await fs.writeFile(requirementsFile, doc, "utf-8");
    console.log(`[agent] ✓ ${requirementsFile}`);

    // Artifact 2: Specification
    console.log(`[agent] Generating specification file...`);
    const specDoc = generateSpec(ticketKey, issueText, transText);
    const specFile = path.join(OUTPUT_DIR, `${ticketKey}-spec.md`);
    await fs.writeFile(specFile, specDoc, "utf-8");
    console.log(`[agent] ✓ ${specFile}`);

    // Artifact 3: Test cases
    console.log(`[agent] Generating test case suite...`);
    const testDoc = generateTestCases(ticketKey, issueText);
    const testFile = path.join(OUTPUT_DIR, `${ticketKey}-testcases.md`);
    await fs.writeFile(testFile, testDoc, "utf-8");
    console.log(`[agent] ✓ ${testFile}`);

    // Artifact 4: E2E design
    console.log(`[agent] Generating E2E design document...`);
    const designDoc = generateDesign(ticketKey, issueText);
    const designFile = path.join(OUTPUT_DIR, `${ticketKey}-design.md`);
    await fs.writeFile(designFile, designDoc, "utf-8");
    console.log(`[agent] ✓ ${designFile}`);

    console.log(`\n[agent] Done — 4 artifacts written to ${OUTPUT_DIR}`);
    console.log(`${"─".repeat(60)}`);
    const preview = doc.length > 600 ? doc.slice(0, 600) + "\n\n… (truncated)" : doc;
    console.log(preview);
    console.log(`${"─".repeat(60)}`);
  } finally {
    await client.close();
  }
}

main().catch((err) => {
  console.error("[agent] Fatal error:", err instanceof Error ? err.message : err);
  process.exit(1);
});
